### ISSUE TITLE
version 1.14.0 use react render not woking, could you help me?

### ISSUE THREAD

**Issue by memberwebm** [kintone-labs/kintone-ui-component#1484] opened 2023-12-08 08:44 UTC
![image](https://github.com/kintone-labs/kintone-ui-component/assets/110653846/42bc9d8d-1bbc-4e38-8da8-dc2ee8477654)
![image](https://github.com/kintone-labs/kintone-ui-component/assets/110653846/4bec92e2-0fa6-4394-9b63-85c703b5c56e)

i want to use react, i could render kuc-button-1-14-0 but kuc-table-1-14-0 not working

**Comment by memberwebm** [comment] 2023-12-08 08:47
@dong0 could you help me?

**Comment by memberwebm** [comment] 2023-12-08 09:54
@TomokoMiyake could you help me?

**Comment by TomokoMiyake** [comment] 2023-12-11 08:40
@memberwebm 
Thank you for the issue registration.
We will check the issue and reply to you.
Please wait for it.

**Comment by memberwebm** [comment] 2023-12-18 09:07
hi @TomokoMiyake ,Have you found the cause?

**Comment by dong0** [comment] 2023-12-19 03:14
Hello, @memberwebm 
I am checking, please wait.
I will reply to you as soon as I have the results.
Thank you.

**Comment by dong0** [comment] 2023-12-20 06:30
Hello, @memberwebm 
We have investigated and found the cause.

The type of table's columns and data is Array.
In React, the array properties cannot be defined like a attribute( columns={column} ).
You need to use a ref to set them.
Please refer to the discussion https://github.com/kintone-labs/kintone-ui-component/discussions/990 (search "Array type property" to find the paragraph quickly).

Below is the sample code and demo image that you can refer to.
```javascript
import "kintone-ui-component";
import React, { useEffect, useRef } from "react";

export const KucTableSample = () => {
  const columns = [
    {
      title: 'Name',
      field: 'name',
      // render: renderName
    },
    {
      title: 'Address',
      field: 'address'
    },
    {
      title: 'Age',
      field: 'age',
      // render: renderAge
    }
  ];
  const data = [
    {
      name: 'john',
      age: 32,
      address: 'New York No. 1 Lake Park'
    },
    {
      name: 'steven',
      age: 22,
      address: 'New York No. 2 Lake Park'
    }
  ];

  const kucTableRef = useRef(null);
  useEffect(() => {
    const table = kucTableRef.current;
    if (table) {
      table.columns = columns;
      table.data = data;
    }
  }, [kucTableRef]);

  return (
    <>
      <kuc-table-1-14-0
        ref={kucTableRef}
        class="kintoneplugin-table"
      />
    </>
  );
};
```

![react-table](https://github.com/kintone-labs/kintone-ui-component/assets/3798705/31fa1ec2-0d88-4ad7-a5cf-ef5134bf8692)

Thank you!

**Comment by memberwebm** [comment] 2023-12-20 06:47
Thank you!

**Comment by TomokoMiyake** [comment] 2024-01-16 07:48
@memberwebm 
I will close this issue because it was resolved.
Thank you!

**Closed by TomokoMiyake** 2024-01-16 07:48 UTC
